version: '3.8'
services:
  jenkins:
    image: jupi15docker/jenkins:latest
    build:
      context: .
      dockerfile: ./docker/dockerfile.jenkins
    container_name: jenkins-container
    restart: unless-stopped
    privileged: true
    user: root
    ports:
      - 8081:8080
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_home:
